-EJERCIO 1 (hay q usar la base de datos base_parcial.sql)
USE sanatorio

BEGIN TRANSACTION;
	BEGIN TRY
		INSERT INTO PACIENTES VALUES(6,'Fernando','Rivera',1,0)
		INSERT INTO LOGG VALUES(0,'ALTA PACIENTE',GETDATE())
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		SELECT
		ERROR_MESSAGE() AS ErrorMessage
		ROLLBACK TRANSACTION
	END CATCH
