CREATE PROCEDURE procedimiento1(
@ConceptoID INT,
@CajaID INT,
@Monto INT,
@Fecha DATE
)
AS
BEGIN
DECLARE @ID INT
SELECT @ID = MAX(MovimientoID) + 1 FROM MOVIMIENTOS
BEGIN TRANSACTION
	BEGIN TRY
		INSERT INTO MOVIMIENTOS VALUES(@ID,@ConceptoID,@CajaID, @Monto, @Fecha)
		UPDATE CAJAS
		SET Saldo = Saldo + @Monto
		WHERE CajaID=@CajaID
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		ROLLBACK
	END CATCH
END